#!/bin/bash

if [ -z $1 ]; then
    echo "No subcommand specified!"
    exit 1
elif [ $1 = "commit" ]; then
    python3 -m gitcommit > /tmp/template
    git commit -t /tmp/template
else
    echo "Subcommand '$1' unknown."
    exit 1
fi
